import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from '../components'


const RenderCards = ({data, title}) => {
  if (data?.length === 0) {
    return <h2 className='font-bold text-[#6449ff] text-xl mt-5 uppercase '>No results found for: <span className='text-[#222328]'>{title}</span></h2>
  } else {
    return (
      <>
      {title && (
        <h2 className='font-medium text-[#666e75] text-xl mb-3'>
          Search results for: <span className='text-[#222328]'>{title}</span>
        </h2>
      )}
      <div className='grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 xs:grid-cols-2 gap-3'>
        {data?.map((post) => (
          <Card key={post.id} {...post} />
        ))}
      </div>
      </>
    )
  }
}

const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)

  const [search, setSearch] = useState('')

  return (
    <section className='max-w-7xl mx-auto'>
    <div>
      <h1 className='text-[32px] font-extrabold text-[#222328]'>The Community Showcase</h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
    </div>
    <div className='mt-16'>
    <FormField />
    </div>
    <div className='mt-10'>
    {loading ? (
      <div className='flex justify-center items-center'>
        <Loader />
      </div>
    ) : (
      <>
      {search && (
        <h2 className='font-medium text-[#666e75] text-xl mb-3'>
          Search results for: <span className='text-[#222328]'>{search}</span>
        </h2>
      )}
      <div className='grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-4 xs:grid-cols-2 gap-3'>
      {search ? (
        <RenderCards data={[]} title='No Search Results found' />
      ): (
        <RenderCards data={[]} title='No Posts found' />
      )}
      </div>
      </>)}
    </div>
    </section>
  )
}

export default Home
